# Clustering Crypto

In [103]:
# Initial imports
import pandas as pd
import hvplot.pandas
from path import Path
import plotly.express as px
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

import numpy as np



### Deliverable 1: Preprocessing the Data for PCA

In [2]:
# Load the crypto_data.csv dataset.
file_name='./data/crypto_data.csv'
crypto_df = pd.read_csv(file_name,index_col=0)

crypto_df.head()

CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [3]:
# Keep all the cryptocurrencies that are being traded.
crypto_df = crypto_df[crypto_df['IsTrading'] == True]
print(len(crypto_df))
crypto_df.head()

1144


CoinName Algorithm  IsTrading ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt       True   PoW/PoS     4.199995e+01              42
365    365Coin       X11       True   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt       True   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       True       PoW              NaN          611000
808        808   SHA-256       True   PoW/PoS     0.000000e+00               0

In [4]:
# Keep all the cryptocurrencies that have a working algorithm.
crypto_df['Algorithm'].unique()

array(['Scrypt', 'X11', 'SHA-256', 'X13', 'Ethash', 'CryptoNight-V7',
       'Equihash', 'SHA-512', 'Multiple', 'X15', 'NIST5', 'Quark',
       'Groestl', 'PoS', 'NeoScrypt', 'SHA3', 'HybridScryptHash256',
       'Scrypt-n', 'PHI1612', 'Lyra2REv2', 'CryptoNight', 'Shabal256',
       'Counterparty', 'Blake', 'Momentum', 'Stanford Folding', 'QuBit',
       'XG Hash', 'M7 POW', 'Curve25519', 'Lyra2RE', 'QUAIT', 'vDPOS',
       'Blake2b', 'BLAKE256', '1GB AES Pattern Search', 'Dagger',
       'CryptoNight-Lite', 'X11GOST', 'SHA-256D', 'POS 3.0',
       'Progressive-n', 'DPoS', 'Lyra2Z', 'X14', 'Time Travel', 'Argon2',
       'Keccak', 'Blake2S', 'Dagger-Hashimoto', '536', 'Argon2d',
       'Cloverhash', 'Skein', 'SkunkHash v2 Raptor',
       'VeChainThor Authority', 'Ouroboros', 'POS 2.0', 'SkunkHash',
       'C11', 'Proof-of-BibleHash', 'SHA-256 + Hive',
       'Proof-of-Authority', 'XEVAN', 'VBFT', 'YescryptR16', 'IMesh',
       'Green Protocol', 'Semux BFT consensus', 'X16R', 'Tribus',


In [5]:
# Remove the "IsTrading" column. 
crypto_df=crypto_df.drop(['IsTrading'],axis=1)
crypto_df.head()

CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42     42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
365    365Coin       X11   PoW/PoS              NaN      2300000000
404    404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
611  SixEleven   SHA-256       PoW              NaN          611000
808        808   SHA-256   PoW/PoS     0.000000e+00               0

In [6]:
# Remove rows that have at least 1 null value.
crypto_df = crypto_df.dropna()
print(len(crypto_df))
crypto_df.head()

685


CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
404     404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
808         808   SHA-256   PoW/PoS     0.000000e+00               0
1337  EliteCoin       X13   PoW/PoS     2.927942e+10    314159265359
BTC     Bitcoin   SHA-256       PoW     1.792718e+07        21000000

In [7]:
# Keep the rows where coins are mined.
crypto_df=crypto_df[crypto_df['TotalCoinsMined']>0]
print(len(crypto_df))
crypto_df.head()

532


CoinName Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      42 Coin    Scrypt   PoW/PoS     4.199995e+01              42
404     404Coin    Scrypt   PoW/PoS     1.055185e+09       532000000
1337  EliteCoin       X13   PoW/PoS     2.927942e+10    314159265359
BTC     Bitcoin   SHA-256       PoW     1.792718e+07        21000000
ETH    Ethereum    Ethash       PoW     1.076842e+08               0

In [8]:
# Create a new DataFrame that holds only the cryptocurrencies names.
crypto_names=pd.DataFrame(crypto_df['CoinName'])
crypto_names.head()

CoinName
42      42 Coin
404     404Coin
1337  EliteCoin
BTC     Bitcoin
ETH    Ethereum

In [9]:
# Drop the 'CoinName' column since it's not going to be used on the clustering algorithm.
crypto_df=crypto_df.drop(['CoinName'],axis=1)
crypto_df.head()

Algorithm ProofType  TotalCoinsMined TotalCoinSupply
42      Scrypt   PoW/PoS     4.199995e+01              42
404     Scrypt   PoW/PoS     1.055185e+09       532000000
1337       X13   PoW/PoS     2.927942e+10    314159265359
BTC    SHA-256       PoW     1.792718e+07        21000000
ETH     Ethash       PoW     1.076842e+08               0

In [10]:
# Use get_dummies() to create variables for text features.
X = pd.get_dummies(crypto_df, columns=['Algorithm','ProofType'])
X.head()

TotalCoinsMined TotalCoinSupply  Algorithm_1GB AES Pattern Search  \
42       4.199995e+01              42                                 0   
404      1.055185e+09       532000000                                 0   
1337     2.927942e+10    314159265359                                 0   
BTC      1.792718e+07        21000000                                 0   
ETH      1.076842e+08               0                                 0   

      Algorithm_536  Algorithm_Argon2d  Algorithm_BLAKE256  Algorithm_Blake  \
42                0                  0                   0                0   
404               0                  0                   0                0   
1337              0                  0                   0                0   
BTC               0                  0                   0                0   
ETH               0                  0                   0                0   

      Algorithm_Blake2S  Algorithm_Blake2b  Algorithm_C11  ...  \
42                    0                  0              0  ...   
404                   0                  0              0  ...   
1337                  0                  0              0  ...   
BTC                   0                  0              0  ...   
ETH                   0                  0              0  ...   

      ProofType_PoW/PoS  ProofType_PoW/PoS   ProofType_PoW/PoW  \
42                    1                   0                  0   
404                   1                   0                  0   
1337                  1                   0                  0   
BTC                   0                   0                  0   
ETH                   0                   0                  0   

      ProofType_PoW/nPoS  ProofType_Pos  ProofType_Proof of Authority  \
42                     0              0                             0   
404                    0              0                             0   
1337                   0              0                             0   
BTC                    0              0                             0   
ETH                    0              0                             0   

      ProofType_Proof of Trust  ProofType_TPoS  \
42                           0               0   
404                          0               0   
1337                         0               0   
BTC                          0               0   
ETH                          0               0   

      ProofType_Zero-Knowledge Proof  ProofType_dPoW/PoW  
42                                 0                   0  
404                                0                   0  
1337                               0                   0  
BTC                                0                   0  
ETH                                0                   0  

[5 rows x 98 columns]

In [11]:
# Standardize the data with StandardScaler().
X_scaled=StandardScaler().fit_transform(X)
print(X_scaled[0:5])

[[-0.11710817 -0.1528703  -0.0433963  -0.0433963  -0.0433963  -0.06142951
  -0.07530656 -0.0433963  -0.06142951 -0.06142951 -0.0433963  -0.0433963
  -0.19245009 -0.06142951 -0.09740465 -0.0433963  -0.11547005 -0.07530656
  -0.0433963  -0.0433963  -0.15191091 -0.0433963  -0.13118084 -0.0433963
  -0.0433963  -0.08703883 -0.0433963  -0.0433963  -0.0433963  -0.0433963
  -0.06142951 -0.0433963  -0.08703883 -0.08703883 -0.08703883 -0.0433963
  -0.13118084 -0.13840913 -0.13840913 -0.0433963  -0.06142951 -0.0433963
  -0.07530656 -0.18168574 -0.0433963  -0.0433963  -0.0433963  -0.07530656
  -0.15826614 -0.31491833 -0.0433963  -0.08703883 -0.07530656 -0.06142951
   1.38675049 -0.0433963  -0.0433963  -0.06142951 -0.0433963  -0.0433963
  -0.0433963  -0.0433963  -0.0433963  -0.0433963  -0.0433963  -0.0433963
  -0.39879994 -0.0433963  -0.18168574 -0.0433963  -0.08703883 -0.08703883
  -0.10680283 -0.0433963  -0.13118084 -0.0433963  -0.0433963  -0.0433963
  -0.0433963  -0.07530656 -0.43911856 -0.04339

### Deliverable 2: Reducing Data Dimensions Using PCA

In [12]:
# Using PCA to reduce dimension to three principal components.
# Initialize PCA model
pca = PCA(n_components=3)
crypto_pca = pca.fit_transform(X_scaled)

print(crypto_pca)

[[-0.33306175  1.00754467 -0.49822519]
 [-0.31639624  1.00767624 -0.49846764]
 [ 2.30923055  1.68284635 -0.66183854]
 ...
 [ 0.31881727 -2.30500466  0.3931012 ]
 [-0.15630009 -1.9547885   0.38739848]
 [-0.28580015  0.79898785 -0.19690725]]


In [13]:
# Create a DataFrame with the three principal components.
# Transform PCA data to DataFrame
pcs_df=pd.DataFrame(data=crypto_pca,columns=['PC1','PC2','PC3'])

#Re-index using cryptoNames
pcs_df['name']=crypto_names.index.tolist()
pcs_df=pcs_df.set_index('name')
pcs_df.index.name = None
pcs_df.head()

PC1       PC2       PC3
42   -0.333062  1.007545 -0.498225
404  -0.316396  1.007676 -0.498468
1337  2.309231  1.682846 -0.661839
BTC  -0.133874 -1.320459  0.068109
ETH  -0.159721 -2.041498  0.383683

### Deliverable 3: Clustering Crytocurrencies Using K-Means

#### Finding the Best Value for `k` Using the Elbow Curve

In [14]:
# Create an elbow curve to find the best value for K.
# Find the best value for K
inertia = []
k = list(range(1, 11))

# Calculate the inertia for the range of K values
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(pcs_df)
    inertia.append(km.inertia_)

# Create the elbow curve
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")

C:\Users\brian\anaconda3\envs\PythonData\lib\site-packages\sklearn\cluster\_kmeans.py:1039: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  "KMeans is known to have a memory leak on Windows "


:Curve   [k]   (inertia)

Running K-Means with `k=4`

In [113]:
# Initialize the K-Means model.
model = KMeans(n_clusters=4, random_state=0)

# Fit the model
model.fit(pcs_df)

# Predict clusters
predictions = model.predict(pcs_df)

In [114]:
# Create a new DataFrame including predicted clusters and cryptocurrencies features.
# Concatentate the crypto_df and pcs_df DataFrames on the same columns.
clustered_df=crypto_df.copy()
clustered_df[['PC1','PC2','PC3']]=pcs_df[['PC1','PC2','PC3']]

#df_iris_pca["class"] = model.labels_
#df_iris_pca.head()

#  Add a new column, "CoinName" to the clustered_df DataFrame that holds the names of the cryptocurrencies. 
clustered_df['CoinName']=crypto_names['CoinName']

#  Add a new column, "Class" to the clustered_df DataFrame that holds the predictions.
clustered_df['Class']=predictions

# Print the shape of the clustered_df
#print(clustered_df.shape)
clustered_df.head(10)

Algorithm ProofType  TotalCoinsMined TotalCoinSupply       PC1  \
42            Scrypt   PoW/PoS     4.199995e+01              42 -0.333062   
404           Scrypt   PoW/PoS     1.055185e+09       532000000 -0.316396   
1337             X13   PoW/PoS     2.927942e+10    314159265359  2.309231   
BTC          SHA-256       PoW     1.792718e+07        21000000 -0.133874   
ETH           Ethash       PoW     1.076842e+08               0 -0.159721   
LTC           Scrypt       PoW     6.303924e+07        84000000 -0.165306   
DASH             X11   PoW/PoS     9.031294e+06        22000000 -0.404638   
XMR   CryptoNight-V7       PoW     1.720114e+07               0 -0.161173   
ETC           Ethash       PoW     1.133597e+08       210000000 -0.158163   
ZEC         Equihash       PoW     7.383056e+06        21000000 -0.156299   

           PC2       PC3          CoinName  Class  
42    1.007545 -0.498225           42 Coin      0  
404   1.007676 -0.498468           404Coin      0  
1337  1.682846 -0.661839         EliteCoin      0  
BTC  -1.320459  0.068109           Bitcoin      3  
ETH  -2.041498  0.383683          Ethereum      3  
LTC  -1.141197  0.038379          Litecoin      3  
DASH  1.221949 -0.482340              Dash      0  
XMR  -2.193377  0.414532            Monero      3  
ETC  -2.041599  0.383677  Ethereum Classic      3  
ZEC  -1.954788  0.387398             ZCash      3

### Deliverable 4: Visualizing Cryptocurrencies Results

#### 3D-Scatter with Clusters

In [115]:
# Creating a 3D-Scatter with the PCA data and the clusters
fig = px.scatter_3d(
    clustered_df,
    x="PC1",
    y="PC2",
    z="PC3",
    color="Class",
    symbol="Class",
    width=800,
    hover_data=["Algorithm"],
    hover_name="CoinName"
)
fig.update_layout(legend=dict(x=0, y=1))
fig.show()

In [116]:
# Create a table with tradable cryptocurrencies.
tradable_table=clustered_df.hvplot.table(columns=[
    'CoinName', 'Algorithm', 'ProofType','TotalCoinSupply','TotalCoinsMined','Class'],
    sortable=True, selectable=True)
tradable_table

:Table   [CoinName,Algorithm,ProofType,TotalCoinSupply,TotalCoinsMined,Class]

In [117]:
# Print the total number of tradable cryptocurrencies.
len(tradable_table)

532

In [118]:
# Scaling data to create the scatter plot with tradable cryptocurrencies.
X_scaled=MinMaxScaler().fit_transform(clustered_df[['TotalCoinSupply','TotalCoinsMined']])
print(X_scaled[0:5])

[[4.20000000e-11 0.00000000e+00]
 [5.32000000e-04 1.06585544e-03]
 [3.14159265e-01 2.95755135e-02]
 [2.10000000e-05 1.81084216e-05]
 [0.00000000e+00 1.08773140e-04]]


In [119]:
# Create a new DataFrame that has the scaled data with the clustered_df DataFrame index.
plot_df=clustered_df
plot_df['TotalCoinSupply']=[i[0] for i in X_scaled]
plot_df['TotalCoinsMined']=[i[1] for i in X_scaled]

plot_df=plot_df.drop(['Algorithm','ProofType','PC1','PC2','PC3'],axis=1)

# Add the "CoinName" column from the clustered_df DataFrame to the new DataFrame.
# YOUR CODE HERE

# Add the "Class" column from the clustered_df DataFrame to the new DataFrame. 
# YOUR CODE HERE

plot_df.head(10)

TotalCoinsMined  TotalCoinSupply          CoinName  Class
42           0.000000     4.200000e-11           42 Coin      0
404          0.001066     5.320000e-04           404Coin      0
1337         0.029576     3.141593e-01         EliteCoin      0
BTC          0.000018     2.100000e-05           Bitcoin      3
ETH          0.000109     0.000000e+00          Ethereum      3
LTC          0.000064     8.400000e-05          Litecoin      3
DASH         0.000009     2.200000e-05              Dash      0
XMR          0.000017     0.000000e+00            Monero      3
ETC          0.000115     2.100000e-04  Ethereum Classic      3
ZEC          0.000007     2.100000e-05             ZCash      3

In [121]:
# Create a hvplot.scatter plot using x="TotalCoinsMined" and y="TotalCoinSupply".
plot_df.hvplot.scatter(x="TotalCoinsMined", y="TotalCoinSupply",
                       by='Class',hover_cols=["CoinName"])


:NdOverlay   [Class]
   :Scatter   [TotalCoinsMined]   (TotalCoinSupply,CoinName)